### ISSUE TITLE
Forma prawna - wyszczególnienie różnic między fundacją, a stowarzyszeniem

### ISSUE THREAD

**Issue by Keij0** [hakierspejs/wiki#1]
W tym momencie strona na wiki nie opisuje jaka jest podstawa prawna działania obydwu form i czym się różnią, warto byłoby to uzupełnić, bo będzie łatwiej wybrać + można dopisać co mówił q3k

**Comment by d33tah** [comment]
@Keij0 zalozysz puste sekcje na to?

**Comment by Keij0** [comment]
@d33tah Główne czy jako header w stronie?

**Comment by Keij0** [comment]
https://github.com/hakierspejs/wiki/wiki/Forma-prawna/0a4cd9af895aad6326491e7af7b01efbb393ca13

**Comment by Keij0** [comment]
Draft sekcji wleciał na wiki

**Comment by d33tah** [comment]
@Keij0 czy issue dalej jest aktualny? Jeśli tak, po czym poznamy kiedy przestał być?

**Comment by Keij0** [comment]
W tym momencie sam w sobie nie jest aktualny, pozostaje wewnętrznie wybrać czy jesteśmy stowarzyszeniem czy fundacją.
