### ISSUE TITLE
PKO don't allow the symbol '-'

### ISSUE THREAD

**Issue by asweeney99** [hakierspejs/wiki#6]
![Screenshot from 2021-01-19 15-22-51](https://user-images.githubusercontent.com/20420065/105054989-820f3500-5a6a-11eb-8b48-e8766add66ce.png)

**Comment by asweeney99** [comment]
Ten sugerowany tytuł dla przelewów nie jest dozwolony w PKO:

Tytuł przelewu: „<pseudonim lub nazwa użytkownika> - Hakierspejs – składka”.

**Comment by asweeney99** [comment]
Jednak to działa:

HAKIERSPEJS - SKŁADKA

**Comment by ghost** [comment]
Pewnie chodzi o ten drugi myślnik, tzn. pierwszy jest krótki - drugi jest długi –

**Comment by d33tah** [comment]
@kujaw good catch! Przekonuje mnie to, zmieniłem ;)
